name: Ruff #Nombre del workflow
on: [push, pull_request] #Eventos que deseamos que dispare el workflow, en nuestro caso push y pull_request
jobs: #Definimos los trabajos que queremos que se ejecuten
  ruff: #Nombre del trabajo
    runs-on: ubuntu-latest #El sistema operativo en el que se ejecutará el trabajo
    steps: 
      - uses: actions/checkout@v3 #Clonar el repositorio en el entorno de ejecución del flujo de trabajo 
      - uses: chartboost/ruff-action@v1 #Comprueba que se siguen las reglas de estilo de Ruff

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r .github/workflows/requirements.txt
      
      - name: Run tests
        run: |
          pytest test/test.py
  
